# Generated by Django 6.0 on 2026-01-03 07:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemResponse",
            fields=[
                (
                    "response_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_type", models.CharField(max_length=32)),
                ("text", models.TextField(blank=True, null=True)),
                ("audio_tokens", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_responses",
            },
        ),
    ]
