# Generated by Django 6.0 on 2025-12-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_gateway", "0003_room_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommember",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
