# Generated by Django 6.0 on 2026-01-03 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VectorEntry',
            fields=[
                ('vector_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', models.JSONField()),
                ('source_type', models.CharField(max_length=32)),
                ('source_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory_service.vectorentry')),
            ],
        ),
    ]
