# # """
# # Django settings for core project.

# # Generated by 'django-admin startproject' using Django 6.0.

# # For more information on this file, see
# # https://docs.djangoproject.com/en/6.0/topics/settings/

# # For the full list of settings and their values, see
# # https://docs.djangoproject.com/en/6.0/ref/settings/
# # """

# # """
# # Django settings for core project.
# # Generated by 'django-admin startproject'
# # """

# # from datetime import timedelta
# # from pathlib import Path

# # # ===============================
# # # BASE DIR
# # # ===============================
# # BASE_DIR = Path(__file__).resolve().parent.parent


# # # ===============================
# # # SECURITY
# # # ===============================
# # SECRET_KEY = "django-insecure-change-this-in-production"
# # DEBUG = True
# # ALLOWED_HOSTS = []


# # # ===============================
# # # APPLICATIONS
# # # ===============================
# # INSTALLED_APPS = [
# #     # Django defaults
# #     "django.contrib.admin",
# #     "django.contrib.auth",
# #     "django.contrib.contenttypes",
# #     "django.contrib.sessions",
# #     "django.contrib.messages",
# #     "django.contrib.staticfiles",
# #     # DRF
# #     "rest_framework",
# #     # Services
# #     "auth_service",
# #     "room_gateway",
# #     "chat_service",
# #     "moderation_service",
# #     "dialogue_service",
# #     "memory_service",
# #     "audio_service",
# # ]


# # # ===============================
# # # MIDDLEWARE
# # # ===============================
# # MIDDLEWARE = [
# #     "django.middleware.security.SecurityMiddleware",
# #     "django.contrib.sessions.middleware.SessionMiddleware",
# #     "django.middleware.common.CommonMiddleware",
# #     "django.middleware.csrf.CsrfViewMiddleware",
# #     "django.contrib.auth.middleware.AuthenticationMiddleware",
# #     "django.contrib.messages.middleware.MessageMiddleware",
# #     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# # ]


# # # ===============================
# # # URL & WSGI
# # # ===============================
# # ROOT_URLCONF = "core.urls"
# # WSGI_APPLICATION = "core.wsgi.application"


# # # ===============================
# # # TEMPLATES
# # # ===============================
# # TEMPLATES = [
# #     {
# #         "BACKEND": "django.template.backends.django.DjangoTemplates",
# #         "DIRS": [],
# #         "APP_DIRS": True,
# #         "OPTIONS": {
# #             "context_processors": [
# #                 "django.template.context_processors.request",
# #                 "django.contrib.auth.context_processors.auth",
# #                 "django.contrib.messages.context_processors.messages",
# #             ],
# #         },
# #     },
# # ]


# # # ===============================
# # # DATABASE
# # # ===============================
# # DATABASES = {
# #     "default": {
# #         "ENGINE": "django.db.backends.sqlite3",
# #         "NAME": BASE_DIR / "db.sqlite3",
# #     }
# # }


# # # ===============================
# # # PASSWORD VALIDATION
# # # ===============================
# # AUTH_PASSWORD_VALIDATORS = [
# #     {
# #         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
# #     },
# #     {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
# #     {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
# #     {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
# # ]


# # # ===============================
# # # INTERNATIONALIZATION
# # # ===============================
# # LANGUAGE_CODE = "en-us"
# # TIME_ZONE = "UTC"
# # USE_I18N = True
# # USE_TZ = True


# # # ===============================
# # # STATIC FILES
# # # ===============================
# # STATIC_URL = "/static/"


# # # ===============================
# # # DEFAULT AUTO FIELD
# # # ===============================
# # DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# # # ===============================
# # # DJANGO REST FRAMEWORK
# # # ===============================
# # REST_FRAMEWORK = {
# #     "DEFAULT_AUTHENTICATION_CLASSES": [
# #         "rest_framework_simplejwt.authentication.JWTAuthentication",
# #     ],
# #     "DEFAULT_PERMISSION_CLASSES": [
# #         "rest_framework.permissions.IsAuthenticated",
# #     ],
# # }


# # # ===============================
# # # SIMPLE JWT
# # # ===============================
# # SIMPLE_JWT = {
# #     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
# #     "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
# #     "AUTH_HEADER_TYPES": ("Bearer",),
# # }
# """
# Django settings for core project.
# Generated by 'django-admin startproject'
# """

# from datetime import timedelta
# from pathlib import Path


# # ===============================
# # BASE DIR
# # ===============================
# BASE_DIR = Path(__file__).resolve().parent.parent


# # ===============================
# # SECURITY
# # ===============================
# SECRET_KEY = "django-insecure-change-this-in-production"
# DEBUG = True
# ALLOWED_HOSTS = []


# # ===============================
# # APPLICATIONS
# # ===============================
# INSTALLED_APPS = [
#     # Django defaults
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     # DRF
#     "rest_framework",
#     # Services
#     "auth_service",
#     "room_gateway",
#     "chat_service",
#     "moderation_service",
#     "dialogue_service",
#     "memory_service",
#     "audio_service",
# ]


# # ===============================
# # MIDDLEWARE
# # ===============================
# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]


# # ===============================
# # URL & WSGI
# # ===============================
# ROOT_URLCONF = "core.urls"
# WSGI_APPLICATION = "core.wsgi.application"


# # ===============================
# # TEMPLATES
# # ===============================
# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     }
# ]


# # ===============================
# # DATABASE
# # ===============================
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# # ===============================
# # PASSWORD VALIDATION
# # ===============================
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "UserAttributeSimilarityValidator"
#         ),
#     },
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "MinimumLengthValidator"
#         ),
#     },
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "CommonPasswordValidator"
#         ),
#     },
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "NumericPasswordValidator"
#         ),
#     },
# ]


# # ===============================
# # INTERNATIONALIZATION
# # ===============================
# LANGUAGE_CODE = "en-us"
# TIME_ZONE = "UTC"
# USE_I18N = True
# USE_TZ = True


# # ===============================
# # STATIC FILES
# # ===============================
# STATIC_URL = "/static/"


# # ===============================
# # DEFAULT AUTO FIELD
# # ===============================
# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# # ===============================
# # DJANGO REST FRAMEWORK
# # ===============================
# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     ],
#     "DEFAULT_PERMISSION_CLASSES": [
#         "rest_framework.permissions.IsAuthenticated",
#     ],
# }


# # ===============================
# # SIMPLE JWT
# # ===============================
# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
#     "AUTH_HEADER_TYPES": ("Bearer",),
# }

from datetime import timedelta
from pathlib import Path

# ===============================
# BASE DIR
# ===============================
BASE_DIR = Path(__file__).resolve().parent.parent

# ===============================
# SECURITY
# ===============================
SECRET_KEY = "django-insecure-change-this-in-production"
DEBUG = True
ALLOWED_HOSTS: list[str] = []

# ===============================
# APPLICATIONS
# ===============================
INSTALLED_APPS = [
    # Django defaults
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # DRF
    "rest_framework",
    # Services
    "auth_service",
    "room_gateway",
    "chat_service",
    "moderation_service",
    "dialogue_service",
    "memory_service",
    "audio_service",
]

# ===============================
# MIDDLEWARE
# ===============================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ===============================
# URL & WSGI
# ===============================
ROOT_URLCONF = "core.urls"
WSGI_APPLICATION = "core.wsgi.application"

# ===============================
# TEMPLATES
# ===============================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ===============================
# DATABASE
# ===============================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ===============================
# PASSWORD VALIDATION
# ===============================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator"),
    },
]

# ===============================
# INTERNATIONALIZATION
# ===============================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ===============================
# STATIC FILES
# ===============================
STATIC_URL = "/static/"

# ===============================
# DEFAULT AUTO FIELD
# ===============================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ===============================
# DJANGO REST FRAMEWORK
# ===============================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# ===============================
# SIMPLE JWT
# ===============================
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}
