# Generated by Django 6.0 on 2026-01-08 07:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_broadcast", "0002_audiobroadcastsession_delete_audiolistener_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_id", models.UUIDField()),
                ("host_id", models.UUIDField()),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("is_live", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="AudioBroadcastSession",
        ),
    ]
