# Generated by Django 6.0 on 2026-01-03 09:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModerationEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("moderator_id", models.UUIDField()),
                (
                    "target_type",
                    models.CharField(
                        choices=[("message", "Message"), ("user", "User")],
                        max_length=16,
                    ),
                ),
                ("target_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("mute", "Mute"),
                            ("soft_delete", "Soft Delete"),
                            ("temp_block", "Temporary Block"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "moderation_events",
            },
        ),
    ]
